### ISSUE TITLE
Chapter 5 example 3 authentication with a third party

### ISSUE THREAD

**Issue by flacoman91** [johnbrett/Getting-Started-with-hapi.js#10]
Hi John, 

I'm trying the example with twitter authentication.

here's the values i see after creating a twitter app.
Consumer Key (API Key)  
Consumer Secret (API Secret)    

is the api key the same as Client ID? 

I'm getting a 500 internal server error when going to the http://127.0.0.1:1337/login page and I don't know how to debug this. 

Any ideas?
Thanks

**Comment by flacoman91** [comment]
Never mind. i figured it out. I needed to have http://127.0.0.1 in the callback url setting on the twitter app page.  It wasn't a required field when filling it out, so I left it blank initially.

**Comment by johnbrett** [comment]
Glad you got sorted Richard, hope it didn't take too long to figure out! :)
